# Generated by Django 3.1.3 on 2021-01-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'basic'), (1, 'medium'), (2, 'hard'), (3, 'extreme')], db_index=True)),
                ('group', models.IntegerField(db_index=True)),
                ('type', models.IntegerField(choices=[(0, 'silgle'), (1, 'multi')])),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
                ('correct', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quiz')),
            ],
        ),
    ]
