# Generated by Django 3.1.3 on 2021-01-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='group',
            new_name='qgroup',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='level',
            new_name='qlevel',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='type',
            new_name='qtype',
        ),
    ]
