# Generated by Django 3.1.3 on 2021-01-29 18:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20210128_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizItem',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Question',
        ),
    ]
