# Generated by Django 3.1.3 on 2021-03-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210208_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-qlevel', 'qgroup']},
        ),
    ]
