# Generated by Django 3.1.3 on 2021-01-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('picture', models.CharField(max_length=256, null=True)),
                ('link', models.CharField(max_length=100)),
                ('sub', models.CharField(default='', max_length=30)),
            ],
            options={
                'unique_together': {('group', 'name')},
            },
        ),
    ]
