# Generated by Django 3.1.3 on 2021-01-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sub',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
