# Generated by Django 3.1.3 on 2021-03-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210109_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['group', 'id']},
        ),
    ]
