# Generated by Django 3.1.3 on 2021-02-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncrypthMethods',
        ),
    ]
