# Generated by Django 3.1.3 on 2021-02-13 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateTimeField(auto_now_add=True)),
                ('game', models.CharField(db_index=True, max_length=250)),
                ('game_id', models.TextField(db_index=True)),
                ('s_result', models.IntegerField(default=0)),
                ('s_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-s_result', 's_time'],
                'unique_together': {('user', 'game', 'game_id')},
            },
        ),
    ]
