# Generated by Django 3.1.3 on 2021-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoring',
            name='game',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
