# Generated by Django 3.1.3 on 2021-01-20 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20210120_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='moderator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='set_moderation', to=settings.AUTH_USER_MODEL, verbose_name='moderator'),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='set_posts', to=settings.AUTH_USER_MODEL, verbose_name='właściciel'),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='post nadrzędny'),
        ),
    ]
