# Generated by Django 3.1.3 on 2021-01-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210121_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='external_link',
            field=models.URLField(default='', max_length=500, verbose_name='link'),
        ),
    ]
