# Generated by Django 3.1.3 on 2021-01-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210121_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.IntegerField(choices=[(0, 'News'), (1, 'Quotation'), (2, 'Forum'), (3, 'Notes'), (4, 'Post'), (5, 'BookPrice'), (6, 'Content')], db_index=True, verbose_name='grupa'),
        ),
    ]
