# Generated by Django 3.1.3 on 2021-01-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210124_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dec_content',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='wartość'),
        ),
    ]
