# Generated by Django 3.1.3 on 2021-01-30 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_auto_20210129_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='negative_reaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negatives', to=settings.AUTH_USER_MODEL, verbose_name='pozytywne'),
        ),
        migrations.AlterField(
            model_name='post',
            name='positive_reaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positives', to=settings.AUTH_USER_MODEL, verbose_name='pozytywne'),
        ),
    ]
