# Generated by Django 3.1.3 on 2021-01-30 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20210130_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='negative_reaction',
        ),
        migrations.RemoveField(
            model_name='post',
            name='positive_reaction',
        ),
        migrations.AddField(
            model_name='post',
            name='negatives',
            field=models.ManyToManyField(default=None, null=True, related_name='negative_reaction', to=settings.AUTH_USER_MODEL, verbose_name='pozytywne'),
        ),
        migrations.AddField(
            model_name='post',
            name='positives',
            field=models.ManyToManyField(default=None, null=True, related_name='positive_reaction', to=settings.AUTH_USER_MODEL, verbose_name='pozytywne'),
        ),
    ]
