# Generated by Django 3.1.3 on 2021-02-08 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0012_auto_20210130_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='negatives',
            field=models.ManyToManyField(default=None, related_name='negative_reaction', to=settings.AUTH_USER_MODEL, verbose_name='pozytywne'),
        ),
        migrations.AlterField(
            model_name='post',
            name='positives',
            field=models.ManyToManyField(default=None, related_name='positive_reaction', to=settings.AUTH_USER_MODEL, verbose_name='pozytywne'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subgroup',
            field=models.CharField(db_index=True, default='', max_length=64, verbose_name='podgrupa'),
        ),
    ]
