# Generated by Django 3.1.3 on 2021-04-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210309_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.IntegerField(choices=[(0, 'News'), (1, 'Quotation'), (2, 'Forum'), (3, 'Notes'), (4, 'Post'), (5, 'BookPrice'), (6, 'Content'), (7, 'Message'), (8, 'Welcome')], db_index=True, verbose_name='grupa'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stage',
            field=models.IntegerField(choices=[(0, 'posted'), (1, 'approved'), (-1, 'rejected'), (2, 'main view post')], db_index=True, default=0, verbose_name='status'),
        ),
    ]
