# Generated by Django 3.1.3 on 2021-01-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_auto_20210115_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='fix',
            field=models.BooleanField(default=True),
        ),
    ]
