# Generated by Django 3.1.3 on 2021-01-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_auto_20210116_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='sudoku',
        ),
        migrations.AddField(
            model_name='block',
            name='sudoku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='sudoku.sudoku'),
        ),
        migrations.RemoveField(
            model_name='cell',
            name='sudoku',
        ),
        migrations.AddField(
            model_name='cell',
            name='sudoku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sudoku.sudoku'),
        ),
    ]
