# Generated by Django 3.1.3 on 2021-01-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0005_cell_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['x', 'y']},
        ),
    ]
